# Generated by Django 3.2.9 on 2021-11-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0002_auto_20211128_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='order_paid',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
