# Generated by Django 3.2.9 on 2021-11-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0005_auto_20211128_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderLine',
        ),
    ]
