# Generated by Django 3.2.9 on 2021-11-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0006_rename_orderitem_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test3', to='primeflix_app.order'),
        ),
    ]
