# Generated by Django 3.2.9 on 2021-11-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0007_orderline_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test3', to='primeflix_app.customer'),
        ),
    ]
