# Generated by Django 3.2.9 on 2021-11-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeflix_app', '0010_alter_orderline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='primeflix_app.customer'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='primeflix_app.product'),
        ),
    ]
